name: Release Erlang Libraries
on:
  push:
    branches: [master]
  pull_request:
    branches: ['**']

env:
  NODEJS_VERSION: '16'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup swagger-codegen
        uses: valitydev/action-setup-swagger-codegen@v0.0.1
        with:
          codegen-version: "2.4.25"
          generator-version: "1.0.1"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODEJS_VERSION }}
          cache: npm

      - name: Install deps
        run: npm install

      - name: Bundle spec and build docsite
        run: npm run build -- build_public

      - name: Generate stubs
        run: |
          mkdir -p out
          echo "Generate ushort stubs"
          swagger-codegen generate -l vality-erlang-client -i build_public/swagger.json -o out/erlang-client-ushort --additional-properties packageName=swag_client_ushort
          swagger-codegen generate -l vality-erlang-server -i build_public/swagger.json -o out/erlang-server-ushort --additional-properties packageName=swag_server_ushort

      - name: Deploy erlang-client-ushort artifact to release branch
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: release/erlang/ushort-client/master
          folder: out/erlang-client-ushort
          commit-message: Release ${{ github.repository }}@${{ github.sha }}

      - name: Deploy erlang-server-ushort artifact to release branch
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: release/erlang/ushort-server/master
          folder: out/erlang-server-ushort
          commit-message: Release ${{ github.repository }}@${{ github.sha }}
